export const data1 = [
  {
    name: "Maio 2023",
    pago: "0",
    "não pago": "0",
    "pago na hora": "0",
  },
  {
    name: "Junho 2023",
    pago: "0",
    "não pago": "0",
    "pago na hora": "0",
  },
  {
    name: "Julho 2023",
    pago: "0",
    "não pago": "0",
    "pago na hora": "0",
  },
  {
    name: "Agosto 2023",
    pago: "0",
    "não pago": "0",
    "pago na hora": "0",
  },
  {
    name: "Setembro 2023",
    pago: "0",
    "não pago": "0",
    "pago na hora": "0",
  },
  {
    name: "Outubro 2023",
    pago: "0",
    "não pago": "0",
    "pago na hora": "0",
  },
  {
    name: "Novembro 2023",
    pago: "0",
    "não pago": "0",
    "pago na hora": "0",
  },
  {
    name: "Dezembro 2023",
    pago: "0",
    "não pago": "0",
    "pago na hora": "0",
  },
  {
    name: "Janeiro 2024",
    pago: "0",
    "não pago": "0",
    "pago na hora": "0",
  },
  {
    name: "Fevereiro 2024",
    pago: "0",
    "não pago": "0",
    "pago na hora": "0",
  },
  {
    name: "Março 2024",
    pago: "22900",
    "não pago": "5200",
    "pago na hora": "22900",
  },
];

export const data2 = [
  {
    name: "Maio 2023",
    dinheiro: "0",
    "transferência bancária": "0",
    "cartão de crédito": "0",
    paypal: "0",
    outros: "0",
    "cartão pré-pago": "0",
  },
  {
    name: "Junho 2023",
    dinheiro: "0",
    "transferência bancária": "0",
    "cartão de crédito": "0",
    paypal: "0",
    outros: "0",
    "cartão pré-pago": "0",
  },
  {
    name: "Julho 2023",
    dinheiro: "0",
    "transferência bancária": "0",
    "cartão de crédito": "0",
    paypal: "0",
    outros: "0",
    "cartão pré-pago": "0",
  },
  {
    name: "Agosto 2023",
    dinheiro: "0",
    "transferência bancária": "0",
    "cartão de crédito": "0",
    paypal: "0",
    outros: "0",
    "cartão pré-pago": "0",
  },
  {
    name: "Setembro 2023",
    dinheiro: "0",
    "transferência bancária": "0",
    "cartão de crédito": "0",
    paypal: "0",
    outros: "0",
    "cartão pré-pago": "0",
  },
  {
    name: "Outubro 2023",
    dinheiro: "0",
    "transferência bancária": "0",
    "cartão de crédito": "0",
    paypal: "0",
    outros: "0",
    "cartão pré-pago": "0",
  },
  {
    name: "Novembro 2023",
    dinheiro: "0",
    "transferência bancária": "0",
    "cartão de crédito": "0",
    paypal: "0",
    outros: "0",
    "cartão pré-pago": "0",
  },
  {
    name: "Dezembro 2023",
    dinheiro: "0",
    "transferência bancária": "0",
    "cartão de crédito": "0",
    paypal: "0",
    outros: "0",
    "cartão pré-pago": "0",
  },
  {
    name: "Janeiro 2024",
    dinheiro: "0",
    "transferência bancária": "0",
    "cartão de crédito": "0",
    paypal: "0",
    outros: "0",
    "cartão pré-pago": "0",
  },
  {
    name: "Fevereiro 2024",
    dinheiro: "0",
    "transferência bancária": "0",
    "cartão de crédito": "0",
    paypal: "0",
    outros: "0",
    "cartão pré-pago": "0",
  },
  {
    name: "Março 2024",
    dinheiro: "200",
    "transferência bancária": "0",
    "cartão de crédito": "1500",
    paypal: "1500",
    outros: "400",
    "cartão pré-pago": "2000",
  },
];

export const data3 = [
  {
    name: "Ana Oliveira",
    value: 19400,
  },
  {
    name: "Gabriel Santos",
    value: 1500,
  },
  {
    name: "Isabela Pereira",
    value: 1500,
  },
  {
    name: "Lucas Costa",
    value: 800,
  },
  {
    name: "Maria Souza",
    value: 800,
  },
  {
    name: "Matheus Silva",
    value: 400,
  },
];